name: tbd_foods
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.0.0+2 # for camera permissions
  http: ^0.13.4 # for connection to python flask server 
  path_provider: ^2.0.11  # or latest version
  camera: ^0.11.0+2
  mobile_scanner: ^5.2.3
  inner_glow: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
