name: tbd_foods
description: "TBD Foods App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.0.0+2 # for camera permissions
  http: ^1.2.2 # for connection to python flask server 
  path_provider: ^2.0.11  # or latest version
  camera: ^0.11.0+2
  mobile_scanner: ^5.2.3
  inner_glow: ^1.0.0
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  dart_openai: ^5.1.0
  flutter_dotenv: ^5.0.2
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^1.0.0
  build_runner: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - .env
